# Install prerequisites.
---

- name: Basic packages.
  apt: name={{ item }} state=present
  with_items:
  - git
  - vim-nox

- name: Programming environment.
  apt: name={{ item }} state=present
  with_items:
  - idle-python3.5
  - python3-pil.imagetk
